-- Vim settings
vim.cmd("set expandtab")
vim.cmd("set tabstop=2")
vim.cmd("set softtabstop=2")
vim.cmd("set shiftwidth=2")
vim.cmd("set number")
vim.cmd("set relativenumber")
vim.cmd("set wrap")
vim.cmd("set linebreak")
vim.cmd("set breakindent")
vim.cmd("set autoindent")
vim.cmd("set mouse=a")
-- vim.cmd("set clipboard+=unnamedplus")
vim.cmd("set ignorecase")
vim.cmd("set smartcase")
vim.cmd("set incsearch")
vim.cmd("set scrolloff=25")
vim.cmd("set signcolumn=yes")
vim.cmd("set completeopt=menuone,noinsert,noselect")
vim.cmd("set history=1000")
vim.cmd("set ruler")
vim.cmd("set cursorline")
vim.cmd("set mouse=a")
vim.cmd("set confirm")
vim.cmd("set undofile")
vim.cmd("set noswapfile")

-- Vim keymaps
-- vim.cmd("nnoremap _ ^")
