set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set number
set relativenumber
set wrap
set linebreak
set breakindent
set autoindent
set mouse=a
set clipboard+=unnamedplus
set ignorecase
set smartcase
set incsearch
set scrolloff=25
set signcolumn=yes
set completeopt=menuone,noinsert,noselect
set history=1000
set ruler
set cursorline
set mouse=a
set confirm
set noundofile
set noswapfile

set showcmd
set showmode
set wildmenu
filetype on
syntax on 
colorscheme onedark 
